# Generated by Django 4.0.5 on 2022-09-06 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_alter_perfil_data_nascimento_alter_perfil_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='idade',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
