# Generated by Django 4.0.5 on 2022-09-22 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0009_alter_produto_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imagem2',
            field=models.URLField(blank=True, null=True, verbose_name='Imagem 2'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.URLField(blank=True, null=True, verbose_name='Imagem 1'),
        ),
    ]
