# Generated by Django 4.0.5 on 2022-10-19 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0011_favorito_itemfavorito'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemfavorito',
            options={'verbose_name': 'Item favorito', 'verbose_name_plural': 'Itens favoritados'},
        ),
        migrations.AddField(
            model_name='itemfavorito',
            name='slug',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
