# Generated by Django 4.0.5 on 2022-10-31 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0001_initial'),
        ('produto', '0012_alter_itemfavorito_options_itemfavorito_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variacao',
            options={'verbose_name': 'Variação', 'verbose_name_plural': 'Variações (obrigatório)'},
        ),
        migrations.AlterField(
            model_name='produto',
            name='categoria_produto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='categoria.categoria', verbose_name='Categoria'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=24),
        ),
        migrations.AlterField(
            model_name='produto',
            name='tipo',
            field=models.CharField(choices=[('N', 'Nenhum'), ('D', 'Destaque'), ('L', 'Lançamento'), ('V', 'Mais Vendido')], default='L', max_length=1),
        ),
        migrations.AlterField(
            model_name='variacao',
            name='nome',
            field=models.CharField(default=1, max_length=3, verbose_name='Nome (Máx de 3 caracteres)'),
            preserve_default=False,
        ),
    ]
