# Generated by Django 4.0.5 on 2022-10-31 14:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0003_pedido_qtd_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='criado',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Criação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='modificado',
            field=models.DateField(auto_now=True, verbose_name='Atualização'),
        ),
    ]
